### ISSUE TITLE
move README.fr-FR.md to README.fr.md

### ISSUE THREAD

**Issue by chanjsq** [J-Ramsey/README.md#1]
Because no `README.fr-XX.md` than `README.fr-FR.md` exists. IMO.

**Comment by J-Ramsey** [comment]
I didn't even begin the french translation. I created the file just to say to myself "I will do the french translation" and also to test the display in GitHub. So the name of the file was chosen inspired by my experience, seeing this format often.

But firstly, I think that standardization of file names is also important in a project and some languages may absolutely need to suggest a variant , and secondly, there is a lot of french variant (See this [Wikipedia](https://en.wikipedia.org/wiki/Varieties_of_French))

But I'll continue to think about it.

**Comment by chanjsq** [comment]
You are right. I forgot the variants. 😄
